# Local repositories
repository=/host/binpkgs/bootstrap
repository=/host/binpkgs
repository=/host/binpkgs/nonfree
repository=/host/binpkgs/debug
repository=/host/binpkgs/d77
repository=/host/binpkgs/hypr-d77
repository=/host/binpkgs/cosmic-d77
